"""empty message

Revision ID: 988c45798d29
Revises: 09b561adc16e
Create Date: 2020-04-08 20:01:50.732668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988c45798d29'
down_revision = '09b561adc16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conc', sa.Float(precision=3, asdecimal=True), nullable=False),
    sa.Column('strain', sa.Integer(), nullable=False),
    sa.Column('terpene', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strain'], ['strain.id'], ),
    sa.ForeignKeyConstraint(['terpene'], ['terpene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assay')
    # ### end Alembic commands ###
