"""empty message

Revision ID: 00ac9ee11efd
Revises: 2aeb107e23e4
Create Date: 2020-03-13 03:02:46.057789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ac9ee11efd'
down_revision = '2aeb107e23e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strain', sa.Column('genetics', sa.Text(), nullable=True))
    op.add_column('strain', sa.Column('lineage', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'strain', ['genetics'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strain', type_='unique')
    op.drop_column('strain', 'lineage')
    op.drop_column('strain', 'genetics')
    # ### end Alembic commands ###
