"""empty message

Revision ID: 2aeb107e23e4
Revises: 9a3e1591cb88
Create Date: 2020-03-13 01:37:10.983617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aeb107e23e4'
down_revision = '9a3e1591cb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strain', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strain', 'image')
    # ### end Alembic commands ###
