"""empty message

Revision ID: 44028e9d9d7c
Revises: bc86559d33c2
Create Date: 2020-01-22 12:50:31.768806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44028e9d9d7c'
down_revision = 'bc86559d33c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compound', 'percent_concentration',
               existing_type=sa.NUMERIC(precision=3, scale=0),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compound', 'percent_concentration',
               existing_type=sa.NUMERIC(precision=3, scale=0),
               nullable=False)
    # ### end Alembic commands ###
