"""empty message

Revision ID: 9a3e1591cb88
Revises: 44028e9d9d7c
Create Date: 2020-03-12 22:38:31.328080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3e1591cb88'
down_revision = '44028e9d9d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compound', 'percent_concentration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compound', sa.Column('percent_concentration', sa.NUMERIC(precision=3, scale=0), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
