"""empty message

Revision ID: b8d381897cc5
Revises: 21c159fcb8c8
Create Date: 2020-01-21 23:58:24.368159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d381897cc5'
down_revision = '21c159fcb8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('compound_name_key', 'compound', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('compound_name_key', 'compound', ['name'])
    # ### end Alembic commands ###
