"""empty message

Revision ID: bc86559d33c2
Revises: b8d381897cc5
Create Date: 2020-01-22 00:10:05.628884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc86559d33c2'
down_revision = 'b8d381897cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('terpene_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.ForeignKeyConstraint(['terpene_id'], ['terpene.id'], ),
    sa.PrimaryKeyConstraint('terpene_id', 'strain_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('strain')
    # ### end Alembic commands ###
