"""empty message

Revision ID: cf235ed7b51c
Revises: 00ac9ee11efd
Create Date: 2020-03-13 13:42:57.021255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'cf235ed7b51c'
down_revision = '00ac9ee11efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    terpenearomas = postgresql.ENUM('herbal', 'pine', 'peppery', 'citrus', 'fruity', 'Sweet', name='terpenearomas')
    terpenearomas.create(op.get_bind())

    op.add_column('terpene', sa.Column('aroma', sa.Enum('herbal', 'pine', 'peppery', 'citrus', 'fruity', 'Sweet', name='terpenearomas'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terpene', 'aroma')

    terpenearomas = postgresql.ENUM('herbal', 'pine', 'peppery', 'citrus', 'fruity', 'Sweet', name='terpenearomas')
    terpenearomas.drop(op.get_bind())
    # ### end Alembic commands ###
