"""empty message

Revision ID: f6f861a2e9b1
Revises: 4e9307190937
Create Date: 2020-06-13 14:16:10.827012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f861a2e9b1'
down_revision = '4e9307190937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('role_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='role_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='role_users_pkey')
    )
    op.drop_table('roles_users')
    # ### end Alembic commands ###
