"""empty message

Revision ID: 09b561adc16e
Revises: 87754c7ed03f
Create Date: 2020-03-18 18:34:55.096136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b561adc16e'
down_revision = '87754c7ed03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('strain_genetics_key', 'strain', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('strain_genetics_key', 'strain', ['genetics'])
    # ### end Alembic commands ###
